from distribucionUniforme import grafica_distribucionUniforme
from distribucionExponencial import grafica_distribucionExponencial
from distribucionGamma import grafica_distribucionGamma
from distribucionNormal import grafica_distribucionNormal
from distribucionBinomial import grafica_distribucionBinomial
from distribucionHipergeometrica import grafica_distribucionHipergeometrica
from distribucionPoisson import grafica_distribucionPoisson
from distribucionEmpiricaDiscreta import grafica_distribucionEmpiricaDiscreta

grafica_distribucionUniforme()
grafica_distribucionExponencial()
grafica_distribucionGamma()
grafica_distribucionNormal()
#pascal
grafica_distribucionBinomial()
grafica_distribucionHipergeometrica()
grafica_distribucionPoisson()
grafica_distribucionEmpiricaDiscreta()
